{% set version = '1.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-genio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/genio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/genio/genio_{{ version }}.tar.gz
  sha256: f4ad6737a9f5cdfea8ac4f9ed8df33fac3c01b15d75e6c71ebceee8ab647fd47

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-dplyr
    - r-readr >=2.0.0
    - r-tibble
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr
    - r-readr >=2.0.0
    - r-tibble

test:
  commands:
    - $R -e "library('genio')"           # [not win]
    - "\"%R%\" -e \"library('genio')\""  # [win]

about:
  home: https://github.com/OchoaLab/genio
  license: GPL-3.0-only
  summary: Implements readers and writers for file formats associated with genetics data.  Reading
    and writing Plink BED/BIM/FAM and GCTA binary GRM formats is fully supported, including
    a lightning-fast BED reader and writer implementations.  Other functions are 'readr'
    wrappers that are more constrained, user-friendly, and efficient for these particular
    applications; handles Plink and Eigenstrat tables (FAM, BIM, IND, and SNP files).  There
    are also make functions for FAM and BIM tables with default values to go with simulated
    genotype data.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: genio
# Title: Genetics Input/Output Functions
# Version: 1.1.2
# Authors@R: person(given = "Alejandro", family = "Ochoa", role = c("aut", "cre"), email = "alejandro.ochoa@duke.edu", comment = c(ORCID = "0000-0003-4928-3403"))
# Description: Implements readers and writers for file formats associated with genetics data.  Reading and writing Plink BED/BIM/FAM and GCTA binary GRM formats is fully supported, including a lightning-fast BED reader and writer implementations.  Other functions are 'readr' wrappers that are more constrained, user-friendly, and efficient for these particular applications; handles Plink and Eigenstrat tables (FAM, BIM, IND, and SNP files).  There are also make functions for FAM and BIM tables with default values to go with simulated genotype data.
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: readr (>= 2.0.0), tibble, dplyr, Rcpp
# LinkingTo: Rcpp
# Suggests: testthat, knitr, rmarkdown, BEDMatrix, snpStats, lobstr
# VignetteBuilder: knitr
# URL: https://github.com/OchoaLab/genio
# BugReports: https://github.com/OchoaLab/genio/issues
# NeedsCompilation: yes
# Packaged: 2023-01-06 16:24:30 UTC; viiia
# Author: Alejandro Ochoa [aut, cre] (<https://orcid.org/0000-0003-4928-3403>)
# Maintainer: Alejandro Ochoa <alejandro.ochoa@duke.edu>
# Repository: CRAN
# Date/Publication: 2023-01-06 23:00:05 UTC
